FROM python:3.12-slim

LABEL maintainer="MohammadHosseinYaghubi"

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONBUFFERED=1

COPY requirements ./requirements

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    build-essential \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    shared-mime-info \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip \
 pip install --no-cache-dir -r requirements/development.txt

COPY . .

RUN chmod +x docker/development/docker-entrypoint.sh

ENTRYPOINT ["./docker/development/docker-entrypoint.sh"]