FROM python:3.12-slim

LABEL maintainer="MohammadHosseinYaghubi"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && apt-get clean \
    build-essential \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    shared-mime-info \
    && rm -rf /var/lib/apt/lists/*

COPY requirements ./requirements

RUN pip install --upgrade pip

RUN pip install \
    -r requirements/production.txt

COPY . .

RUN chmod +x docker/production/docker-entrypoint.sh

ENTRYPOINT ["./docker/production/docker-entrypoint.sh"]